# Generated by Django 3.1 on 2020-09-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0010_uid_db_index'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('newuser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
